### ISSUE TITLE
Serial Chapter Launch

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#10]
**Child issues**
- [x] Available vs Coming Soon chapters
- [x] Chapter Count field
- [x] Unpublished Chapters Toast
- [x] Classroom Page
- [x] Email notifications
- [x] Learner Dashboard

**Web links**
- [Lo-Fi Mock](https://docs.google.com/document/d/1ICgLeyn1NukvjkRb4o5Pimv9gdME_G6tislia1oD9EY/edit#heading=h.zfdnhljgwfzo)
- [Creator User Flow Screenshots](https://docs.google.com/presentation/d/1qbcj1mAmPkYAxeElDJS4wiaaQS9jwulAzD_0SkLnnz8/edit#slide=id.g11ab1902fbc_0_0)
- [Rio's Figma File](https://www.figma.com/file/cpscKq6oe6STtz6IYkcjd7/Serial-Chapter-Launches?node-id=0%3A1)
- [PRD](https://docs.google.com/document/d/1Uh_CJRhGE4IM7c0ENdmXkoMD0YtGqFsl1ObR6vvmxdY/edit#)

**Approvals**
- [X] UX lead (Mindi)
- [X] UXW lead (Dana)
- [X] PM (Diana)

**Comment by RioChanHY** [comment]
Classroom Page and Learner Dashboard are **done**

**Comment by fionafyzeng** [comment]
@seanlip please tick Classroom Page and Learner Dashboard off of the Child issues list.

@RioChanHY we're looking forward to the progress of **_Email notifications_** :)

**Comment by seanlip** [comment]
done! (re ticking)

**Comment by RioChanHY** [comment]
working on a mobile version

**Comment by Sumita23** [comment]
I've completed my UX writing pass--it's ready for review

**Comment by ghost** [comment]
@danapj Have you reviewed Sumita's UXW pass?

**Comment by ghost** [comment]
@RioChanHY Is there anything still pending on this project from the UX design side, or can we mark this as handed off to PM?

**Comment by RioChanHY** [comment]
I have passed it to Dana and let her comment and view it. I think it will
pass soon.

**Comment by dchen97** [comment]
Filed issue for development - https://github.com/oppia/oppia/issues/17434
