### ISSUE TITLE
Transfer & Fill-in Tokens on the Design System Page

### ISSUE THREAD

**Issue by tydesignit** [oppia/design-team#110]
**Platform**
Oppia Web | Oppia Android

### **Note: Made individual issues based on the following list. Do not need this.** 

**Describe the request**
The team is tasked with filling in tokens (layout, typography, colors, iconography, avatars, and effects) for the design system. This will be used as a starting point to further progress into deeper design system issues.

**Context for the request**
This is a relatively new feature however assets will be drawn from existing projects to begin.

- What is the broader user journey that this feature fits into?
This issue lies in the designer's journey of struggling or wasting time finding the correct asset efficiently.

- What is the current user experience like (where is the user located before they encounter this feature)? Feel free to add screenshots.
Currently, designers will grab assets from [Project 2](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?type=design&node-id=6050-159194&mode=design&t=zLmFsjizv3mGPtoy-0), look at the current product (web/mobile) or grab from other projects that may have a solution.

**Tasks Reference**
Layout - Suzie
Typography - Queena
Color - Conor
Iconography - Tyler
Avatars - Russell
Effects - Vivian

**Link to PRD**
Please link to the PRD here.

**Information about deadlines/priorities**
If this feature is time-sensitive, please explain why.
If applicable, please also provide the deadline for when the full design (including text content) needs to be completed by.

Each member will complete their assigned task by next week before our Monday meeting (12/18/2023).

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved (Android mocks should include dark mode)
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: N/A (for design style guide projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by seanlip** [comment]
Closing as not needed (see comment in description).
