### ISSUE TITLE
[Exploration Player] Re-design the progress bar to accommodate multiple checkpoints  (sub-issue #93)

### ISSUE THREAD

**Issue by rflore** [oppia/design-team#151]
**Platform**
Oppia Web

**Describe the request**
Explore and re-design the progress bar to accommodate the range of checkpoints displayed. Currently, lessons have between 2 and 8 checkpoints. More research is needed to determine the min and max of the checkpoints and what can be displayed based on the breakpoint.

**Context for the request**
A subset of Submission #93

![image](https://github.com/oppia/design-team/assets/122065646/7eda50d4-a9fd-4766-a0d7-8a914f9f3d10)

**Link to PRD**
N/A

**Information about deadlines/priorities**
No deadline as of yet.

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved 
- [ ] UX Writing approved
- [ ] Design Systems approved
- [ ] Product approved

For a design project to be completed, it needs approval from UXD, UXW and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):

- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by seanlip** [comment]
Merged into #93. Closing.
