### ISSUE TITLE
Content Audit [Web/Mobile] [UXW]

### ISSUE THREAD

**Issue by danapj** [oppia/design-team#26]
### Task Overview 

**Task Description (Deliverable):** Do a content audit to ensure adherence to the style guide 
**Priority:** Medium -- to do as a background task. If there are other content writing requests that come in, address those first
**Deadline:** - 

**Audit Template to use (PLEASE MAKE A COPY):** [https://docs.google.com/document/d/1drc2-GjpkKWu2Xgodb1z66OQQ5k2NdiTzXl03aGgSkA/edit](Google Doc)

**Next Milestones:** 
- (Dana) Assign remaining tasks to (new) writers (target: mid/end Aug) 

### Tasklist

- [ ] Homepage
- [ ] Learner Pages - Megan 
- [ ] Partnerships Pages - Dana 
- [ ] Donor Pages 
- [ ] Volunteer Pages 
- [ ] Parent / Facilitator Pages -  [Janine](https://docs.google.com/document/d/1qeFKP3iOUcC6ubY3hho9hPymaYPOayDU0yGNGT8Bpfg/edit)

**Comment by danapj** [comment]
### 1 Aug Update

- Dana will assign these tasks to new writers as and when they join Oppia

**Comment by danapj** [comment]
### 4 Aug update 
- **Megan** will take up the learner-facing pages. Clarified on Discord that this can include the interface copy on the lessons 9though Sean says there's another ongoing review for lesson content). Will provide Dana an idea of her next milestone. 
- **Janine** will continue with homepage and pick up the parent / facilitator pages

**Comment by danapj** [comment]
22 Sep update - Learner page updates are done, and pending Sean/Diana's thoughts

**Comment by ghost** [comment]
Progress on the website's content audit can be accessed via this [Google Doc.](https://docs.google.com/document/d/1Ir25hzhJ28UenSeCj8hid8YI4QCwQxxW9gtkpiYYc0w/edit#heading=h.l4b4d21s1rxu)

**Comment by danapj** [comment]
as discussed with sean on 25 Jul, I will close this and file as separate issues focused on specific stylistic issues across the projects.
