### ISSUE TITLE
[Translation Submitters] Copy Paste Concept Card (sub-issue #5)

### ISSUE THREAD

**Issue by IMHieuVo** [oppia/design-team#66]
**Platform**
Oppia Web

**Describe the Request**
It is not clear how translators should copy and paste concept cards.

![Image](https://user-images.githubusercontent.com/117132709/223325572-f9943262-b1d2-4cbc-87cc-fa2b295cb413.png)

**Context for the Request**
A subset of Submission Workflow #43.

**Link to PRD**
https://docs.google.com/document/d/1gzA9jJVlPt-DHxXwZXOQaoeN2mjFo8Qni0In193ypLI/edit

**DESIGN APPROVAL CHECKLIST -- DO NOT EDIT.**

- [ ] UX Design approved
- [ ] UX Writing approved
- [ ] Design Systems Team approved
- [ ] Product approved

_For a design project to be completed, it needs approval from UXD, UXW, DS and PM. Please tag the following reviewers when your project is ready (at least one reviewer for each of the 4 bullet points below):_
- UXD: @rflore / @S4v8n (for Web projects)
- UXW: @stepmalt
- Design systems: @qluuu / @celestinetales
- PM: @seanlip

**Comment by kmuir1991** [comment]
@IMHieuVo is this still being worked on? Went ahead and assigned myself as designated UXW since I've worked on copy tool-related projects previously.

**Comment by IMHieuVo** [comment]
Currently, no one is on this project.

**Comment by Kwam98** [comment]
@seanlip hi sean, I was assigned this  issue and was wondering what copy cards are and which copy in the image  needed clarification. Thanks!

**Comment by seanlip** [comment]
Hi @Kwam98, I think this actually needs a designer, in order to think through how to present the "copy flow". I'm not sure UXW can work on this project in isolation.

/cc @rflore @IMHieuVo Do you have other projects for @Kwam98, or a designer who could be assigned to this project?

**Comment by seanlip** [comment]
(Merged this issue into #65, per discussion with Web UX design leads.)
